#!/usr/bin/env python
"""
normalize_items_yaml.py

Bridge script for LodyLand items → legacy resources.yml.

Goals:
  - Scan app/data/items/*.yml
  - Collect all items with kind: resource
  - Generate app/data/resources.yml in the LEGACY format used by:
      - ResourceDef / seed_resources_from_yaml()
  - DO NOT touch craft/item logic (that's handled elsewhere)

Expected item structure (in app/data/items/*.yml):

  items:
    branch:
      key: branch
      kind: resource
      label: Branch
      description: A small branch...
      icon: /static/assets/img/resources/branch.png
      unlock_min_level: 0
      base_cooldown: 10.0
      base_sell_price: 2
      enabled: true
      unlock_description: Always available at level 0.

Only items with `kind: resource` are exported to resources.yml.

Extra:
  - With the flag --json, this script outputs a JSON report instead of
    human logs. This is used by a global “normalize_all” runner.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List
import json
import sys

import yaml

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

THIS_FILE = Path(__file__).resolve()
# .../app/data/items/normalize_items_yaml.py
DATA_ROOT = THIS_FILE.parents[2] / "data"          # app/data
ITEMS_ROOT = DATA_ROOT / "items"                   # app/data/items
OUTPUT_FILE = DATA_ROOT / "resources.yml"          # app/data/resources.yml

# app/ (parent de data)
APP_ROOT = DATA_ROOT.parent
# app/static
STATIC_ROOT = APP_ROOT / "static"

ITEMS_MERGED_FILE = DATA_ROOT / "items.yml"   

# ---------------------------------------------------------------------------
# Small reporter helper (collect logs + control printing)
# ---------------------------------------------------------------------------

class Reporter:
    def __init__(self, json_mode: bool = False) -> None:
        self.json_mode = json_mode
        self.infos: List[str] = []
        self.warnings: List[str] = []
        self.errors: List[str] = []

    def info(self, msg: str) -> None:
        self.infos.append(msg)
        if not self.json_mode:
            print(msg)

    def warn(self, msg: str) -> None:
        # normalise en "⚠ ..." pour cohérence
        if not msg.startswith("⚠"):
            msg = "⚠ " + msg
        self.warnings.append(msg)
        if not self.json_mode:
            print(msg)

    def error(self, msg: str) -> None:
        # normalise en "❌ ..." pour cohérence
        if not msg.startswith("❌"):
            msg = "❌ " + msg
        self.errors.append(msg)
        if not self.json_mode:
            print(msg)


def _items_to_yaml_text(all_items: Dict[str, Dict[str, Any]]) -> str:
    """
    Build the merged items.yml content.

    Structure:
      items:
        key_a:
          ...
        key_b:
          ...
    """
    lines: List[str] = []
    lines.append("# NOTE:")
    lines.append("#   This file is GENERATED by app/data/items/normalize_items_yaml.py.")
    lines.append("#   Do NOT edit this file by hand.")
    lines.append("#   Edit item definitions in app/data/items/*.yml instead.")
    lines.append("")
    lines.append("items:")
    lines.append("")

    # Sort by key for deterministic output
    for key in sorted(all_items.keys()):
        cfg = dict(all_items[key])  # shallow copy

        # Ensure key is present and normalized
        cfg["key"] = key

        # Dump this item as YAML block
        block = yaml.dump({key: cfg}, sort_keys=False, allow_unicode=True)
        # block will be like:
        # key:
        #   foo: ...
        #   bar: ...
        # We want it under "items:" with indentation.
        for line in block.splitlines():
            if not line.strip():
                continue
            lines.append("  " + line)

        lines.append("")  # blank line between items

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_items_from_file(path: Path, rep: Reporter) -> Dict[str, Dict[str, Any]]:
    """
    Load items from a YAML file.

    Accepted formats:

    A) Standard:

       items:
         slug_a:
           key: ...
           kind: resource
           ...
         slug_b:
           ...

    B) Flat dict (fallback):

       slug_a:
         key: ...
         kind: resource
         ...
       slug_b:
         ...

    Returns a dict { item_key: cfg }.
    """
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except Exception as e:  # noqa: BLE001
        raise ValueError(f"ERROR in YAML syntax: {path}\n{e}")

    if data is None:
        rep.info(f"    ↳ (empty YAML in {path}, skipped)")
        return {}

    if not isinstance(data, dict):
        raise ValueError(
            f"Invalid top-level structure in {path}: expected a mapping, "
            f"got {type(data).__name__}."
        )

    # Preferred: "items" block
    items_block = data.get("items")
    if items_block is None:
        # Fallback: consider the whole mapping as slug -> cfg
        items_block = data

    if not isinstance(items_block, dict):
        raise ValueError(
            f"Invalid 'items' structure in {path}: expected a dict, got "
            f"{type(items_block).__name__}."
        )

    result: Dict[str, Dict[str, Any]] = {}

    for slug, cfg in items_block.items():
        if not isinstance(cfg, dict):
            raise ValueError(
                f"Item '{slug}' in {path} must be a dict, got {type(cfg).__name__}."
            )

        key = (cfg.get("key") or str(slug)).strip()
        if not key:
            raise ValueError(
                f"Item '{slug}' in {path} has an empty or missing key."
            )

        if key in result:
            rep.warn(
                f"WARNING: duplicate item key '{key}' in {path} "
                f"(already collected from another entry in the same file)."
            )

        result[key] = cfg

    return result


def _collect_all_items(rep: Reporter) -> Dict[str, Dict[str, Any]]:
    """
    Scan app/data/items/**.yml (récursif).

    On prend :
      app/data/items/*.yml
      app/data/items/resources/*.yml
      app/data/items/whatever/*.yml
    """
    if not ITEMS_ROOT.exists():
        raise SystemExit(f"❌ items root folder not found: {ITEMS_ROOT}")

    all_items: Dict[str, Dict[str, Any]] = {}

    rep.info(f"\nScanning item YAML under (recursive): {ITEMS_ROOT}\n")

    # 🔥 AVANT : ITEMS_ROOT.glob("*.yml")
    # 🔥 MAINTENANT : scan récursif
    for path in sorted(ITEMS_ROOT.rglob("*.yml")):
        # Skip backup files if any
        if path.name.endswith(".bak"):
            continue

        rep.info(f"  • Loading {path}")

        try:
            fragment = _load_items_from_file(path, rep)
        except ValueError:
            # On laisse remonter à main() pour marquer une erreur structurelle
            raise

        if not fragment:
            rep.info(f"    ↳ (no items found in {path}, skipped)")
            continue

        for key, cfg in fragment.items():
            if key in all_items:
                rep.warn(
                    f"WARNING: duplicate item key '{key}' from {path} "
                    f"(overwriting previous definition)."
                )
            all_items[key] = cfg

        rep.info(f"    ↳ {len(fragment)} item(s) loaded")

    rep.info(f"\n→ Collected {len(all_items)} item(s) in total.\n")
    return all_items

def _resolve_icon_path(icon: str) -> Path | None:
    """
    Convertit une chaîne icon (ex: "/static/assets/img/items/resources/foo.png"
    ou "static/assets/img/items/resources/foo.png" ou "foo.png")
    en chemin disque absolu sous app/static.

    Retourne None si on ne peut pas la résoudre proprement.
    """
    if not icon:
        return None

    icon = icon.strip()
    if not icon:
        return None

    # 1) "/static/..." → app/static/...
    if icon.startswith("/static/"):
        rel = icon.lstrip("/")  # "static/..."
        return APP_ROOT / rel

    # 2) "static/..." → app/static/...
    if icon.startswith("static/"):
        return APP_ROOT / icon

    # 3) Sinon : on suppose un simple filename → dossier ressources items
    #    app/static/assets/img/items/resources/<icon>
    return STATIC_ROOT / "assets" / "img" / "items" / "resources" / icon


def _validate_resource_icons(resources: List[Dict[str, Any]], rep: Reporter) -> None:
    """
    Pour chaque resource, vérifie que le fichier d'icône existe physiquement.

    Ajoute un warning si le fichier est manquant :
      "image file not found for item 'gold_leaf' (icon=..., resolved=...)"
    """
    for res in resources:
        icon = (res.get("icon") or "").strip()
        if not icon:
            # pas d'icône définie → on ignore (tu peux en faire un warning si tu veux)
            continue

        resolved = _resolve_icon_path(icon)
        if resolved is None or not resolved.exists():
            rep.warn(
                f"image file not found for item '{res.get('key')}' "
                f"(icon={icon}, resolved={resolved})"
            )



def _build_legacy_resource_entry(item_key: str, cfg: Dict[str, Any]) -> Dict[str, Any]:
    """
    Build a single resource entry for legacy resources.yml from an item cfg.

    Legacy format expects fields:
      key, label, description, icon,
      unlock_min_level, base_cooldown, base_sell_price,
      enabled, unlock_description
    """
    label = (cfg.get("label") or item_key).strip()
    description = cfg.get("description") or ""
    icon = cfg.get("icon") or ""

    # Default values for legacy fields
    unlock_min_level = int(cfg.get("unlock_min_level") or 0)
    base_cooldown = float(cfg.get("base_cooldown") or 10.0)
    # We accept either base_sell_price or sell_price
    base_sell_price = cfg.get("base_sell_price", cfg.get("sell_price", 0))

    try:
        base_sell_price = int(base_sell_price)
    except Exception:
        base_sell_price = 0

    enabled = bool(cfg.get("enabled", True))
    unlock_description = cfg.get("unlock_description") or ""

    entry = {
        "key": item_key,
        "label": label,
        "base_cooldown": base_cooldown,
        "base_sell_price": base_sell_price,
        "unlock_min_level": unlock_min_level,
        "enabled": enabled,
        "icon": icon,
    }

    if description:
        entry["description"] = description
    if unlock_description:
        entry["unlock_description"] = unlock_description

    return entry


def _build_resources_yaml(all_items: Dict[str, Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Create the list of legacy resources from collected items.

    Only items with kind: resource are exported.
    """
    resources: List[Dict[str, Any]] = []

    for key, cfg in sorted(all_items.items()):
        kind = (cfg.get("kind") or "").strip().lower()
        if kind != "resource":
            continue
        entry = _build_legacy_resource_entry(key, cfg)
        resources.append(entry)

    return resources


def _resources_to_yaml_text(resources: List[Dict[str, Any]]) -> str:
    """
    Convert a list of resources to the final YAML text for resources.yml.
    """
    lines: List[str] = []
    lines.append("# NOTE:")
    lines.append("#   This file is GENERATED by app/data/items/normalize_items_yaml.py.")
    lines.append("#   Do NOT edit this file by hand.")
    lines.append("#   Edit item definitions in app/data/items/*.yml instead.")
    lines.append("")
    lines.append("resources:")
    lines.append("")

    yaml_block = yaml.dump(resources, sort_keys=False, allow_unicode=True)
    for line in yaml_block.splitlines():
        if not line.strip():
            lines.append(line)
        else:
            lines.append("  " + line)

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------

def main(argv: List[str] | None = None) -> int:
    if argv is None:
        argv = sys.argv[1:]

    json_mode = "--json" in argv
    rep = Reporter(json_mode=json_mode)

    ok = True
    resources: List[Dict[str, Any]] = []
    structural_error_msg: str | None = None
    all_items: Dict[str, Dict[str, Any]] = {}

    try:
        # 1) Collect all items
        all_items = _collect_all_items(rep)

        if not all_items:
            rep.warn("No items found at all, nothing to write.")
            resources = []
        else:
            # 2) Build legacy resources from items
            resources = _build_resources_yaml(all_items)

        # 3) Validate icons for resources.yml
        _validate_resource_icons(resources, rep)

    except SystemExit as e:
        ok = False
        structural_error_msg = str(e)
    except Exception as e:
        ok = False
        structural_error_msg = str(e)

    if not ok:
        if structural_error_msg:
            rep.error(structural_error_msg)

    resource_count = len(resources)

    # 4) Write resources.yml if we have resources
    if ok and resources:
        yaml_text = _resources_to_yaml_text(resources)
        rep.info(f"→ Will write {resource_count} resource(s) to {OUTPUT_FILE}")

        if OUTPUT_FILE.exists():
            backup = OUTPUT_FILE.with_suffix(".yml.bak")
            backup.write_text(OUTPUT_FILE.read_text(encoding="utf-8"), encoding="utf-8")
            rep.info(f"Backup created: {backup}")

        OUTPUT_FILE.write_text(yaml_text, encoding="utf-8")
        rep.info(f"✓ resources.yml generated at {OUTPUT_FILE}\n")
    elif ok and not resources:
        rep.warn("OK but no resources to write, resources.yml will not be updated.\n")

    # 5) Always write items.yml if we collected items
    if ok and all_items:
        items_yaml = _items_to_yaml_text(all_items)
        rep.info(f"→ Will write {len(all_items)} item(s) to {ITEMS_MERGED_FILE}")

        if ITEMS_MERGED_FILE.exists():
            backup_items = ITEMS_MERGED_FILE.with_suffix(".yml.bak")
            backup_items.write_text(
                ITEMS_MERGED_FILE.read_text(encoding="utf-8"), encoding="utf-8"
            )
            rep.info(f"Backup created: {backup_items}")

        ITEMS_MERGED_FILE.write_text(items_yaml, encoding="utf-8")
        rep.info(f"✓ items.yml generated at {ITEMS_MERGED_FILE}\n")

    # 6) JSON summary for global normalizer
    if json_mode:
        summary = {
            "ok": ok,
            "errors": rep.errors,
            "warnings": rep.warnings,
            "infos": rep.infos,
        }
        # Single valid JSON object on stdout
        print(json.dumps(summary, ensure_ascii=True))

    return 0 if ok else 1

if __name__ == "__main__":
    sys.exit(main())