"""add index on tiles.player_id

Revision ID: 33b69ee51ca5
Revises: 2d8dc6b415db
Create Date: 2025-11-12 09:09:59.795723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b69ee51ca5'
down_revision: Union[str, Sequence[str], None] = '2d8dc6b415db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tiles_player_id'), 'tiles', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tiles_player_id'), table_name='tiles')
    # ### end Alembic commands ###
