"""init tables (clean)

Revision ID: 8e2b69f69074
Revises: 
Create Date: 2025-11-12 21:51:13.733696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e2b69f69074'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('diams', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('last_daily', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('resource_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('resource', sa.String(length=30), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'resource', name='uix_player_resource')
    )
    op.create_index(op.f('ix_resource_stocks_player_id'), 'resource_stocks', ['player_id'], unique=False)
    op.create_index(op.f('ix_resource_stocks_resource'), 'resource_stocks', ['resource'], unique=False)
    op.create_table('tiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('resource', sa.String(length=30), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('cooldown_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tiles_player_id'), 'tiles', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tiles_player_id'), table_name='tiles')
    op.drop_table('tiles')
    op.drop_index(op.f('ix_resource_stocks_resource'), table_name='resource_stocks')
    op.drop_index(op.f('ix_resource_stocks_player_id'), table_name='resource_stocks')
    op.drop_table('resource_stocks')
    op.drop_table('players')
    # ### end Alembic commands ###
