"""resource_defs table

Revision ID: aad3951569e5
Revises: 8e2b69f69074
Create Date: 2025-11-12 23:05:01.827285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad3951569e5'
down_revision: Union[str, Sequence[str], None] = '8e2b69f69074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_defs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('base_cooldown', sa.Integer(), nullable=False),
    sa.Column('base_sell_price', sa.Integer(), nullable=False),
    sa.Column('unlock_min_level', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_defs_key'), 'resource_defs', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_defs_key'), table_name='resource_defs')
    op.drop_table('resource_defs')
    # ### end Alembic commands ###
