"""add unlock_rules

Revision ID: b65b72ff0400
Revises: ea6fde935c80
Create Date: 2025-11-13 18:29:20.570596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b65b72ff0400'
down_revision: Union[str, Sequence[str], None] = 'ea6fde935c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('daily_streak', sa.Integer(), nullable=False))
    op.add_column('players', sa.Column('best_streak', sa.Integer(), nullable=False))
    op.add_column('resource_defs', sa.Column('unlock_rules', sa.JSON().with_variant(sa.Text(), 'sqlite'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_defs', 'unlock_rules')
    op.drop_column('players', 'best_streak')
    op.drop_column('players', 'daily_streak')
    # ### end Alembic commands ###
