"""add xp to player

Revision ID: d21e821f3d0e
Revises: 33b69ee51ca5
Create Date: 2025-11-12 10:22:46.124964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21e821f3d0e'
down_revision: Union[str, Sequence[str], None] = '33b69ee51ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('xp', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'xp')
    # ### end Alembic commands ###
